from database import SessionLocal
from models import Skill

db = SessionLocal()

skills_data = [
    # ===== Programming Languages =====
    ("Python", "technical"),
    ("Java", "technical"),
    ("C", "technical"),
    ("C++", "technical"),
    ("C#", "technical"),
    ("JavaScript", "technical"),
    ("TypeScript", "technical"),
    ("SQL", "technical"),
    ("R", "technical"),
    ("Go", "technical"),
    ("Rust", "technical"),
    ("Swift", "technical"),
    ("Kotlin", "technical"),
    ("PHP", "technical"),
    ("Scala", "technical"),
    ("Ruby", "technical"),
    ("MATLAB", "technical"),
    ("Shell Scripting", "technical"),
    ("Solidity", "technical"),
    ("Dart", "technical"),
    ("Perl", "technical"),
    ("Lua", "technical"),
    ("Haskell", "technical"),
    ("Assembly", "technical"),
    ("COBOL", "technical"),

    # ===== Web Development =====
    ("HTML", "technical"),
    ("CSS", "technical"),
    ("Tailwind CSS", "technical"),
    ("Bootstrap", "technical"),
    ("SASS/SCSS", "technical"),
    ("GraphQL", "technical"),
    ("REST APIs", "technical"),
    ("WebSockets", "technical"),
    ("OAuth", "technical"),
    ("JWT Authentication", "technical"),
    ("Web Accessibility", "technical"),
    ("Responsive Design", "technical"),
    ("Progressive Web Apps", "technical"),
    ("Web Performance Optimization", "technical"),
    ("Browser Dev Tools", "technical"),
    ("CORS", "technical"),

    # ===== Frontend Frameworks & Libraries =====
    ("React", "technical"),
    ("Next.js", "technical"),
    ("Vue.js", "technical"),
    ("Angular", "technical"),
    ("Svelte", "technical"),
    ("Redux", "technical"),
    ("Zustand", "technical"),
    ("React Query", "technical"),
    ("Webpack", "technical"),
    ("Vite", "technical"),
    ("Storybook", "technical"),
    ("Three.js", "technical"),

    # ===== Backend Frameworks =====
    ("Django", "technical"),
    ("FastAPI", "technical"),
    ("Flask", "technical"),
    ("Node.js", "technical"),
    ("Express", "technical"),
    ("Spring Boot", "technical"),
    ("Laravel", "technical"),
    ("Ruby on Rails", "technical"),
    ("ASP.NET", "technical"),
    ("NestJS", "technical"),
    ("Gin", "technical"),
    ("Fiber", "technical"),

    # ===== Mobile Development =====
    ("React Native", "technical"),
    ("Flutter", "technical"),
    ("Android Development", "technical"),
    ("iOS Development", "technical"),
    ("Expo", "technical"),
    ("SwiftUI", "technical"),
    ("Jetpack Compose", "technical"),

    # ===== Databases =====
    ("MySQL", "technical"),
    ("PostgreSQL", "technical"),
    ("MongoDB", "technical"),
    ("Redis", "technical"),
    ("Elasticsearch", "technical"),
    ("Cassandra", "technical"),
    ("Firebase", "technical"),
    ("Supabase", "technical"),
    ("SQLite", "technical"),
    ("DynamoDB", "technical"),
    ("CockroachDB", "technical"),
    ("Neo4j", "technical"),
    ("InfluxDB", "technical"),
    ("MariaDB", "technical"),
    ("Oracle Database", "technical"),
    ("MS SQL Server", "technical"),
    ("Database Design", "technical"),
    ("Query Optimization", "technical"),
    ("Database Indexing", "technical"),
    ("Stored Procedures", "technical"),

    # ===== Data & Analytics =====
    ("Pandas", "technical"),
    ("NumPy", "technical"),
    ("Scikit-learn", "technical"),
    ("TensorFlow", "technical"),
    ("PyTorch", "technical"),
    ("Keras", "technical"),
    ("Data Visualization", "technical"),
    ("Statistics", "technical"),
    ("Machine Learning", "technical"),
    ("Deep Learning", "technical"),
    ("Natural Language Processing", "technical"),
    ("Computer Vision", "technical"),
    ("Data Wrangling", "technical"),
    ("Feature Engineering", "technical"),
    ("A/B Testing", "technical"),
    ("Predictive Modeling", "technical"),
    ("Time Series Analysis", "technical"),
    ("Data Storytelling", "technical"),
    ("ETL Pipelines", "technical"),
    ("Data Governance", "technical"),
    ("Big Data", "technical"),
    ("Apache Spark", "technical"),
    ("Apache Kafka", "technical"),
    ("Apache Airflow", "technical"),
    ("Hadoop", "technical"),
    ("dbt", "technical"),
    ("Data Modeling", "technical"),
    ("Data Warehousing", "technical"),
    ("Exploratory Data Analysis", "technical"),
    ("Bayesian Statistics", "technical"),
    ("Hypothesis Testing", "technical"),

    # ===== AI & LLMs =====
    ("Prompt Engineering", "technical"),
    ("LLM Fine-tuning", "technical"),
    ("RAG Systems", "technical"),
    ("AI Ethics", "technical"),
    ("Reinforcement Learning", "technical"),
    ("Generative AI", "technical"),
    ("Hugging Face", "technical"),
    ("LangChain", "technical"),
    ("OpenAI API", "technical"),
    ("Vector Databases", "technical"),
    ("Embeddings", "technical"),
    ("MLflow", "technical"),
    ("Model Deployment", "technical"),
    ("AI Safety", "technical"),

    # ===== DevOps & Infrastructure =====
    ("Git", "technical"),
    ("Docker", "technical"),
    ("Kubernetes", "technical"),
    ("CI/CD", "technical"),
    ("Terraform", "technical"),
    ("Ansible", "technical"),
    ("Jenkins", "technical"),
    ("GitHub Actions", "technical"),
    ("Linux", "technical"),
    ("Nginx", "technical"),
    ("Monitoring & Logging", "technical"),
    ("Infrastructure as Code", "technical"),
    ("Site Reliability Engineering", "technical"),
    ("Helm", "technical"),
    ("Prometheus", "technical"),
    ("Grafana", "technical"),
    ("ELK Stack", "technical"),
    ("Vagrant", "technical"),
    ("GitLab CI", "technical"),
    ("ArgoCD", "technical"),
    ("Istio", "technical"),

    # ===== Cloud Platforms & Services =====
    ("AWS", "technical"),
    ("Azure", "technical"),
    ("GCP", "technical"),
    ("Serverless Architecture", "technical"),
    ("Cloud Security", "technical"),
    ("Microservices", "technical"),
    ("System Design", "technical"),
    ("AWS Lambda", "technical"),
    ("AWS S3", "technical"),
    ("AWS EC2", "technical"),
    ("AWS RDS", "technical"),
    ("Azure DevOps", "technical"),
    ("Google BigQuery", "technical"),
    ("Cloudflare", "technical"),
    ("Vercel", "technical"),
    ("Netlify", "technical"),
    ("DigitalOcean", "technical"),

    # ===== Security =====
    ("Cybersecurity", "technical"),
    ("Penetration Testing", "technical"),
    ("Network Security", "technical"),
    ("OWASP", "technical"),
    ("Cryptography", "technical"),
    ("Vulnerability Assessment", "technical"),
    ("Identity & Access Management", "technical"),
    ("Zero Trust Security", "technical"),
    ("SOC Operations", "technical"),
    ("Incident Response", "technical"),
    ("Threat Modeling", "technical"),
    ("Security Auditing", "technical"),
    ("Burp Suite", "technical"),
    ("Wireshark", "technical"),
    ("Metasploit", "technical"),
    ("Nmap", "technical"),
    ("SIEM", "technical"),
    ("Firewall Management", "technical"),
    ("PKI", "technical"),

    # ===== BI & Analytics Tools =====
    ("Power BI", "technical"),
    ("Tableau", "technical"),
    ("Looker", "technical"),
    ("Google Analytics", "technical"),
    ("Excel", "technical"),
    ("Google Sheets", "technical"),
    ("Mixpanel", "technical"),
    ("Amplitude", "technical"),
    ("Metabase", "technical"),
    ("Superset", "technical"),
    ("Redash", "technical"),
    ("Domo", "technical"),
    ("Qlik", "technical"),

    # ===== Design Tools =====
    ("Figma", "technical"),
    ("Adobe XD", "technical"),
    ("Adobe Photoshop", "technical"),
    ("Adobe Illustrator", "technical"),
    ("Adobe Premiere Pro", "technical"),
    ("Adobe After Effects", "technical"),
    ("Adobe InDesign", "technical"),
    ("Adobe Lightroom", "technical"),
    ("Sketch", "technical"),
    ("Canva", "technical"),
    ("Blender", "technical"),
    ("Cinema 4D", "technical"),
    ("InVision", "technical"),
    ("Zeplin", "technical"),
    ("Framer", "technical"),
    ("Spline", "technical"),
    ("Procreate", "technical"),
    ("DaVinci Resolve", "technical"),
    ("Final Cut Pro", "technical"),
    ("CapCut", "technical"),

    # ===== Design Skills =====
    ("User Research", "technical"),
    ("Wireframing", "technical"),
    ("Prototyping", "technical"),
    ("Usability Testing", "technical"),
    ("Information Architecture", "technical"),
    ("Design Systems", "technical"),
    ("Typography", "technical"),
    ("Color Theory", "technical"),
    ("Brand Identity Design", "technical"),
    ("Motion Design", "technical"),
    ("Interaction Design", "technical"),
    ("Visual Design", "technical"),
    ("Accessibility Design", "technical"),
    ("Design Thinking", "technical"),
    ("Heuristic Evaluation", "technical"),
    ("Eye Tracking Research", "technical"),
    ("Design Critique", "technical"),

    # ===== Marketing Tools & Platforms =====
    ("HubSpot", "technical"),
    ("Salesforce Marketing Cloud", "technical"),
    ("Google Ads", "technical"),
    ("Meta Ads", "technical"),
    ("Mailchimp", "technical"),
    ("Klaviyo", "technical"),
    ("ActiveCampaign", "technical"),
    ("Hootsuite", "technical"),
    ("Buffer", "technical"),
    ("SEMrush", "technical"),
    ("Ahrefs", "technical"),
    ("Moz", "technical"),
    ("Google Search Console", "technical"),
    ("Google Tag Manager", "technical"),
    ("Hotjar", "technical"),
    ("Optimizely", "technical"),
    ("Segment", "technical"),
    ("Sprout Social", "technical"),
    ("LinkedIn Ads", "technical"),
    ("TikTok Ads", "technical"),

    # ===== Marketing Skills =====
    ("SEO", "technical"),
    ("SEM", "technical"),
    ("Content Marketing", "technical"),
    ("Email Marketing", "technical"),
    ("Social Media Marketing", "technical"),
    ("Paid Advertising", "technical"),
    ("Copywriting", "technical"),
    ("Marketing Analytics", "technical"),
    ("Conversion Rate Optimization", "technical"),
    ("Affiliate Marketing", "technical"),
    ("Influencer Marketing", "technical"),
    ("Marketing Automation", "technical"),
    ("Brand Strategy", "technical"),
    ("Go-to-Market Strategy", "technical"),
    ("Content Creation", "technical"),
    ("Video Marketing", "technical"),
    ("Community Management", "technical"),
    ("PR & Communications", "technical"),
    ("Growth Marketing", "technical"),
    ("Customer Segmentation", "technical"),
    ("Funnel Optimization", "technical"),

    # ===== Business & Strategy Skills =====
    ("Business Strategy", "technical"),
    ("Market Research", "technical"),
    ("Competitive Analysis", "technical"),
    ("Business Development", "technical"),
    ("Product Strategy", "technical"),
    ("OKRs", "technical"),
    ("KPI Tracking", "technical"),
    ("Business Writing", "soft"),
    ("Proposal Writing", "soft"),
    ("Requirements Gathering", "technical"),
    ("Process Improvement", "technical"),
    ("Change Management", "technical"),
    ("Risk Management", "technical"),
    ("Strategic Planning", "technical"),
    ("SWOT Analysis", "technical"),
    ("Business Modeling", "technical"),
    ("P&L Management", "technical"),
    ("Partnership Development", "technical"),
    ("Contract Negotiation", "technical"),

    # ===== Product Management =====
    ("Product Roadmapping", "technical"),
    ("User Story Writing", "technical"),
    ("Backlog Management", "technical"),
    ("Sprint Planning", "technical"),
    ("Customer Discovery", "technical"),
    ("Prioritization Frameworks", "technical"),
    ("Product Analytics", "technical"),
    ("Feature Scoping", "technical"),
    ("Competitive Benchmarking", "technical"),
    ("Product Launch", "technical"),
    ("Stakeholder Management", "soft"),
    ("Executive Presentations", "soft"),

    # ===== Project & Operations Tools =====
    ("JIRA", "technical"),
    ("Asana", "technical"),
    ("Notion", "technical"),
    ("Confluence", "technical"),
    ("Trello", "technical"),
    ("Monday.com", "technical"),
    ("ClickUp", "technical"),
    ("Airtable", "technical"),
    ("Linear", "technical"),
    ("Basecamp", "technical"),
    ("Microsoft Project", "technical"),
    ("Smartsheet", "technical"),

    # ===== Project & Operations Skills =====
    ("Project Management", "technical"),
    ("Agile", "technical"),
    ("Scrum", "technical"),
    ("Kanban", "technical"),
    ("Lean Operations", "technical"),
    ("Six Sigma", "technical"),
    ("Supply Chain Management", "technical"),
    ("Procurement", "technical"),
    ("Vendor Management", "technical"),
    ("Logistics Management", "technical"),
    ("Inventory Management", "technical"),
    ("Quality Assurance", "technical"),
    ("BPM", "technical"),
    ("ERP Systems", "technical"),
    ("SAP", "technical"),
    ("ServiceNow", "technical"),
    ("Salesforce CRM", "technical"),

    # ===== Finance Tools & Skills =====
    ("Financial Modeling", "technical"),
    ("Financial Analysis", "technical"),
    ("Valuation", "technical"),
    ("Budgeting & Forecasting", "technical"),
    ("Accounting", "technical"),
    ("Tax Compliance", "technical"),
    ("Auditing", "technical"),
    ("Investment Analysis", "technical"),
    ("Portfolio Management", "technical"),
    ("Risk Assessment", "technical"),
    ("GAAP", "technical"),
    ("IFRS", "technical"),
    ("QuickBooks", "technical"),
    ("Xero", "technical"),
    ("Bloomberg Terminal", "technical"),
    ("Corporate Finance", "technical"),
    ("Mergers & Acquisitions", "technical"),
    ("Private Equity", "technical"),
    ("Financial Reporting", "technical"),
    ("Cost Accounting", "technical"),
    ("Cash Flow Management", "technical"),
    ("Equity Research", "technical"),
    ("Derivatives", "technical"),
    ("Fixed Income", "technical"),

    # ===== HR Tools & Skills =====
    ("Talent Acquisition", "technical"),
    ("Interviewing", "technical"),
    ("Onboarding", "technical"),
    ("Performance Management", "technical"),
    ("Employee Relations", "technical"),
    ("Compensation Design", "technical"),
    ("HR Compliance", "technical"),
    ("Workforce Planning", "technical"),
    ("Learning & Development", "technical"),
    ("Diversity & Inclusion", "technical"),
    ("Organizational Design", "technical"),
    ("People Analytics", "technical"),
    ("Workday", "technical"),
    ("BambooHR", "technical"),
    ("ADP", "technical"),
    ("Greenhouse ATS", "technical"),
    ("Lever ATS", "technical"),
    ("Culture Amp", "technical"),
    ("Employee Engagement", "technical"),
    ("Succession Planning", "technical"),

    # ===== Legal Skills =====
    ("Contract Drafting", "technical"),
    ("Legal Research", "technical"),
    ("Regulatory Compliance", "technical"),
    ("Intellectual Property Law", "technical"),
    ("Data Privacy Law", "technical"),
    ("Corporate Law", "technical"),
    ("Litigation Support", "technical"),
    ("Due Diligence", "technical"),
    ("Legal Writing", "technical"),
    ("GDPR Compliance", "technical"),
    ("Employment Law", "technical"),
    ("Environmental Law", "technical"),
    ("Anti-money Laundering", "technical"),
    ("Contract Management", "technical"),
    ("Legal Operations", "technical"),

    # ===== Communication & Soft Skills =====
    ("Communication", "soft"),
    ("Problem Solving", "soft"),
    ("Critical Thinking", "soft"),
    ("Leadership", "soft"),
    ("Teamwork", "soft"),
    ("Time Management", "soft"),
    ("Adaptability", "soft"),
    ("Creativity", "soft"),
    ("Attention to Detail", "soft"),
    ("Decision Making", "soft"),
    ("Conflict Resolution", "soft"),
    ("Negotiation", "soft"),
    ("Public Speaking", "soft"),
    ("Active Listening", "soft"),
    ("Mentoring", "soft"),
    ("Emotional Intelligence", "soft"),
    ("Cross-functional Collaboration", "soft"),
    ("Self-motivation", "soft"),
    ("Analytical Thinking", "soft"),
    ("Customer Empathy", "soft"),
    ("Strategic Thinking", "soft"),
    ("Accountability", "soft"),
    ("Growth Mindset", "soft"),
    ("Presentation Skills", "soft"),
    ("Written Communication", "soft"),
    ("Research Skills", "soft"),
    ("Networking", "soft"),
    ("Coaching", "soft"),
    ("Facilitation", "soft"),
    ("Cultural Awareness", "soft"),
    ("Work Ethic", "soft"),
    ("Resourcefulness", "soft"),
]

for name, category in skills_data:
    normalized = name.lower().strip()

    existing = db.query(Skill).filter_by(normalized_name=normalized).first()
    if not existing:
        skill = Skill(
            name=name,
            normalized_name=normalized,
            category=category
        )
        db.add(skill)
        print(f"[+] Added: {name} ({category})")
    else:
        print(f"[*] Already exists: {name}")

db.commit()
db.close()

print("[OK] Skills seeded successfully!")